# Generated by Django 2.0.3 on 2018-04-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0004_auto_20180420_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='Autonomous',
            field=models.BooleanField(choices=[(False, 'Off'), (True, 'On')], default=False),
        ),
    ]
