# Generated by Django 2.0.3 on 2018-04-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqua', '0005_status_autonomous'),
    ]

    operations = [
        migrations.CreateModel(
            name='reading_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField()),
                ('plant_temp', models.IntegerField()),
                ('humidity', models.CharField(max_length=10)),
                ('ph', models.IntegerField()),
            ],
        ),
    ]
